#!/bin/bash

####################################################################
#Set env variables
####################################################################

INSTDIR=$(pwd);
echo "Installation directory = $INSTDIR";
echo "std::string INSTDIR=\"$INSTDIR\";" > Installation_directory.h
INCL="-I ./include/Eigen_3.3.1/ \
      -I ./include/openbabel_3.1.1/build/bin/ \
      -I ./include/vmd-1.9.3/build/bin/ \
      -I ./include/packmol-20.14.0/"
LIB="-L./include/vmd-1.9.3/build/lib -lm -g3 -w"
GCC="g++ -std=c++17"

####################################################################
#Install Polymer builder scripts
####################################################################

$GCC $INCL $LIB Polymer_builder.cpp -o Polymer_builder
$GCC $INCL $LIB packmol_mol2.cpp -o packmol_mol2
$GCC $INCL $LIB generate_lammps_files.cpp -o generate_lammps_files
